### ISSUE TITLE
載入T5m模型ckpt時，出現『not an sstable (bad magic number)』錯誤!!

### ISSUE THREAD

**Issue by fox88-tw** [bojone/t5_in_bert4keras#2]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py in NewCheckpointReader(filepattern)

RuntimeError: not an sstable (bad magic number)

During handling of the above exception, another exception occurred:

OpError                                   Traceback (most recent call last)
9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/py_checkpoint_reader.py in error_translator(e)

OpError: not an sstable (bad magic number)`
---------------------------------------------------------------------------

載入路徑
config_path = '/content/drive/My Drive/T5m_Pre-model/mt5_base_config.json'
checkpoint_path = '/content/drive/My Drive/T5m_Pre-model/model.ckpt-1000000'
spm_path = '/content/drive/My Drive/T5m_Pre-model/sentencepiece_cn.model'
keep_tokens_path = '/content/drive/My Drive/T5m_Pre-model/sentencepiece_cn_keep_tokens.json'

網路上除錯方式，皆指向修改ckpt檔名，將model.ckpt後贅詞刪除即可。並不適用，因早已參照劍大code上所寫的，將".data-00000-00016"贅詞移除；且即使將"-1000000"移除，還是會發生同樣問題。

版本：
google colab
tensorflow==1.14.0
bert4keras==0.9.1
sentencepiece==0.1.94

**Comment by fox88-tw** [comment]
我找到 問題點了!! 是我下載 ckpt 檔時，並沒有下載完全所導致.....

**Comment by dzapologize** [comment]
大佬，请问去哪里下载ckpt可以下载完整的model.ckpt-1000000呀？我这边服务器和网盘都是下载的model.ckpt-1000000.data-00000-of-00016到model.ckpt-1000000.data-00015-of-00016
