### ISSUE TITLE
苏神您好能把训练数据格式分享一下嘛？

### ISSUE THREAD

**Issue by fogCrow** [bojone/t5_in_bert4keras#4]
苏神您好，您的文章对我帮助很大，非常感谢您。

在看您这篇文章时，由于我英语差劲，看论文原著吃力。您方便将您文章中的train.tsv、val.tsv、test.tsv分享一下嘛，我现在没有头绪去构建样本，万分感谢。

或者您也可以把这三个数据集挑几条出来，展示一下，这样可以方便我们初学者更好的学习您的代码。非常感谢。

**Comment by bojone** [comment]
https://github.com/bojone/t5_in_bert4keras/blob/main/data_sample.tsv

“更好地学习代码”应该要读懂代码，理解代码generator所需要的数据格式，然后根据自己的数据格式写出自己的generator，而不是问别人的数据格式应该如何。

**Comment by fogCrow** [comment]
谢谢您！

> https://github.com/bojone/t5_in_bert4keras/blob/main/data_sample.tsv
> 
> “更好地学习代码”应该要读懂代码，理解代码generator所需要的数据格式，然后根据自己的数据格式写出自己的generator，而不是问别人的数据格式应该如何。
