### ISSUE TITLE
测试样例

### ISSUE THREAD

**Issue by zhenhao-huang** [bojone/t5_in_bert4keras#6]
怎么测试t5_in_bert4keras的样例

**Comment by bojone** [comment]
不明白你要表达啥？啥叫“测试t5_in_bert4keras的样例”？你要是跑示例脚本的话，直接跑 https://github.com/bojone/t5_in_bert4keras/blob/main/task_autotitle_csl.py 不就行了？

**Comment by zhenhao-huang** [comment]
> 不明白你要表达啥？啥叫“测试t5_in_bert4keras的样例”？你要是跑示例脚本的话，直接跑 https://github.com/bojone/t5_in_bert4keras/blob/main/task_autotitle_csl.py 不就行了？
这个跑完了，但是没有样例生成，例如类似cpm_ml样例生成

**Comment by bojone** [comment]
> > 不明白你要表达啥？啥叫“测试t5_in_bert4keras的样例”？你要是跑示例脚本的话，直接跑 https://github.com/bojone/t5_in_bert4keras/blob/main/task_autotitle_csl.py 不就行了？
> > 这个跑完了，但是没有样例生成，例如类似cpm_ml样例生成

1、清楚你在做什么任务；
2、理解 task_autotitle_csl.py 代码；
3、达到你的需求。
