### ISSUE TITLE
model训练报错，提升AttributeError: 'generator' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by tiandiweizun** [bojone/t5_in_bert4keras#8]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: win10
- 你使用的**Python**版本: 3.6.5
- 你使用的**Tensorflow**版本:  1.13.2
- 你使用的**Keras**版本: 2.2.4 
- 你使用的**bert4keras**版本: 0.9.1
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**:t5-small

### 核心代码
```python
model.fit(
        train_generator.forfit(),
        steps_per_epoch=len(train_generator),
        epochs=epochs,
        callbacks=[evaluator]
    )
```

### 输出信息
```shell
AttributeError: 'generator' object has no attribute 'ndim'
CreateFile() Error: 2
```

### 自我尝试
model.fit_generator 可以运行，发现您这边的实验是在keras2.3.1进行的，查看了2.3.1 keras model.fit的源码，发现其兼容了2.2.4的fit和fit_generator，其先行判断了fit的对象是否为generator，然后底层再进行相应的调用，不知是否如此。

**Comment by bojone** [comment]
2.2.4要将model.fit改为model.fit_generator
